backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"  
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "الأعمال"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "عنوان المشروع", name: "title", widget: "string"}
      - {label: "وصف", name: "description", widget: "text"}
      - {label: "صورة", name: "image", widget: "image"}

